### ISSUE TITLE
Query Error

### ISSUE THREAD

**Issue by mashalahmad** [sotorrent/db-scripts#1]
Im trying to see the post versions like the example in utorrent19 challenge paper. when I  execute this query im not getting value of **RootPostHistoryId** like in Fig 3 part 1 in the paper. I tried with different PostHistoryId but each time I get the same value in RootPostHistoryId as I mention on PostHistoryId. 

Im running this query on BigQuery and attaching the screen short as well
SELECT * FROM [sotorrent-org:2018_09_23.PostBlockVersion] 
where PostHistoryId=3758880 
AND (PredEqual is Null or PredEqual=0)
ORDER BY PostHistoryId ASC , LocalId ASC;
![issue](https://user-images.githubusercontent.com/31829812/46732342-1e8bdf80-cc85-11e8-854d-9ccf7f2d2d0d.jpg)

**Comment by sbaltes** [comment]
Some clarifications:
* The `PostId` identifies a post (question or answer). In your example, it's [this](https://stackoverflow.com/a/1874638) answer with `PostId` 1874638.
* The `PostHistoryId` identifies a post version. In case of your example, the post has only one version (you can see this on the website, there is no "edited ..." link below the post).
* `PredEqual` is `NULL` if a post block does not have a predecessor (obviously the case for the three post blocks in your example, because the post has only one version).

If you now look at the [question](https://stackoverflow.com/q/1874569) for the answer in your example, you see that is has more than one version. Click on `edited Dec 9 '09 at 19:27` to see those versions. You can also use [this](https://stackoverflow.com/posts/1874569/revisions) link. To retrieve the post block versions using *SOTorrent*, execute the following query (I would recommend to use the standard SQL syntax):

```
#standardsql
SELECT *
FROM `sotorrent-org.2018_09_23.PostBlockVersion`
WHERE PostId=1874569
ORDER BY PostHistoryId ASC , LocalId ASC;
```

![2018-10-10 13_36_26-window](https://user-images.githubusercontent.com/10498957/46733782-87795480-cc91-11e8-8fbf-4e5537a8bbed.png)

If you now want to trace the code snippet with `LocalId` 6 in the most recent post version (`class Ticket ....`), you can use the `RootPostHistoryId` 3759134 and `RootLocalId` 6. This means that the first post version in which this snippet appeared was version 3759134 and the location of the snippet in that version was 6 (just like in the most recent version). All later code block versions refer to this initial or "root" version.

To retrieve all versions of this snippet, you can use the following query:

```
#standardsql
SELECT *
FROM `sotorrent-org.2018_09_23.PostBlockVersion`
WHERE RootPostHistoryId=3759134 AND RootLocalId=6
ORDER BY PostHistoryId ASC;
```

![2018-10-10 13_43_46-window](https://user-images.githubusercontent.com/10498957/46734109-8b59a680-cc92-11e8-9707-057c6eb68020.png)

Since `PredEqual` is `true` for all versions except the first, you can see that this snippet has never been changed. 

I hope this helps. If not, don't hesitate to comment on this issue again.

**Comment by mashalahmad** [comment]
thanks a lot for such a detailed clarification :)
