### ISSUE TITLE
sotorrent20_03: Incomplete PostVersion records

### ISSUE THREAD

**Issue by Alfusainey** [sotorrent/db-scripts#21]
If I import the `sotorrent20_03.PostVersion` table into my local DB, i get a total of  `67,470,976` records while the total number of records of the same table on BigQuery is `75,887,884`. So about `8,416,908` are missing in the data dump file on Zenodo.

Can you please confirm? I noticed this when trying to get the creationdates of post block versions  inside the `PostBlockVersion` table using their corresponding PostHistoryIds.

**Comment by sbaltes** [comment]
Thanks for reporting this!
Strange, because I'm using the same file for Zenodo and the BigQuery import. Maybe something went wrong when updating the Zenodo dataset. I'll look into this and get back to you.

**Comment by sbaltes** [comment]
Update: I'm not sure what exactly is wrong with the Zenodo file, but I can confirm that the number in BigQuery is correct, because it matches the value in the corresponding test case (just search for 75887884):
https://github.com/sotorrent/posthistory-extractor/commit/a3dcd1e89d8d27008b8132f81ef5ab09cf0f669d#diff-057ce430ca61073db25474a2578a40f07750f230c1fd8497aaeef684b6dfb3c0R200
I'll post another update once I've figured out the Zenodo issue.

**Comment by sbaltes** [comment]
I'm currently importing version 2020-03-15 locally, which might take a day or two.

**Comment by Alfusainey** [comment]
> I'm currently importing version 2020-03-15 locally, which might take a day or two.

thanks for taking the time to investigate this

**Comment by sbaltes** [comment]
I've now managed to import table `PostVersion` with the correct row count:

![2021-02-13 20_09_20-Window](https://user-images.githubusercontent.com/10498957/107859085-8cd5a380-6e37-11eb-939d-970b7b0719c7.png)

The problem was a bug in the import scripts (missing column that was added to the dataset):

https://github.com/sotorrent/db-scripts/commit/96c00e3138cce190285d95554c83d95799860d88#diff-ee8850cf0119a928369f5f95b0626df38875fb77c14f413586d6d0edf657884f

So I can confirm that the data is complete, you just have to consider the additional column when importing the file.
I've contacted Zenodo to get the script updated in the archives.
Please re-open this issue if you need further information.

**Comment by Alfusainey** [comment]
thanks @sbaltes it worked after adding the `Comment` column. Thank you

**Comment by sbaltes** [comment]
Great, happy to hear that!
