### ISSUE TITLE
Separating repository name and repository owner name

### ISSUE THREAD

**Issue by JafarAkhondali** [sotorrent/db-scripts#3]
I think it would be nice to separate repository name and repository owner name into two columns in `PostReferenceGH` table

**Comment by sbaltes** [comment]
I implemented this for the new release:

![2018-10-28 07_36_44-google bigquery](https://user-images.githubusercontent.com/10498957/47612896-83687780-da84-11e8-9fab-ec0fabfb0078.png)

A also kept the merged repository name, because people may already rely on that column in their scripts. I may drop it after the MSR mining challenge is over.

Until the new release is out, you can use this snippet to split column `RepoName`:

```
#standardSQL
SELECT
  RepoArray[OFFSET(0)] AS RepoOwner,
  RepoArray[OFFSET(1)] AS RepoName
FROM (
  SELECT SPLIT(RepoName, "/") as RepoArray
  FROM `sotorrent-org.gh_so_references_2018_09_23.PostReferenceGH`
);
```
